version: 1.0.0.{build}

# clone directory
clone_folder: c:\projects\DarkConvert

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: DarkConvert.sln
  verbosity: normal

# scripts to run after build
before_build:
  - nuget restore
after_build:
  - cd c:\projects\DarkConvert\DarkConvert\bin\Release\
  - 7z a c:\Projects\DarkConvert\DarkConvert.7z * -t7z m0=lzma -mx=9 -mfb=64 -md=32m -ms=on
  - cd c:\Projects\DarkConvert

artifacts:
  - path: DarkConvert.7z
    name: DarkConvert.7z
